- name: make sure exomiser dir exists
  file: path=/var/lib/exomiser state=directory

- name: gather some stats on the state of exomiser localy
  stat: path=/home/vagrant/sync/exomiser/{{ exomiser }}-distribution.zip
  register: exomiser_zip

- name: download exomiser zip
  get_url: dest=/home/vagrant/sync/exomiser/exomiser.zip url=ftp://ftp.sanger.ac.uk/pub/resources/software/exomiser/downloads/exomiser/{{ exomiser }}-distribution.zip
  when: exomiser_zip.stat.exists == False

- name: unzip exomiser
  unarchive: copy=no src=/home/vagrant/sync/exomiser/{{ exomiser }}-distribution.zip dest=/var/lib/exomiser creates=/var/lib/exomiser/{{ exomiser }}.BETA

- name: clone patient-network
  git: repo=git@github.com:phenotips/patient-network.git dest=/root/patient-network clone=yes depth=1

# todo: restart services when appropriate
