---
- name: install epel
  yum: name=epel-release state=present

- name: install git
  yum: name=git state=present

- name: install java7
  yum: name=java-1.7.0-openjdk-headless state=present

- name: install unzip
  yum: name=unzip state=present

- name: install maven
  yum: name=maven state=present

- name: install tomcat
  yum: name=tomcat state=present
- include: phenomecentral.yml

#################
## SET UP TOMCAT
# 
- name: copy tomcat config
  copy: src=catalina-root.xml dest=/etc/tomcat/Catalina/localhost/ROOT.xml owner=tomcat group=tomcat


### These files are non-standard on phenomecentral
#hibernate.cfg.xml
#xwiki.cfg
#xwiki.properties
#web.xml
